name: nico_resturant
description: Nico Resturant Interactive App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  fluro: ^1.5.1
  cached_network_image: ^1.1.1
  smooth_star_rating: ^1.0.3
  image_picker: ^0.6.1
  google_sign_in:
  firebase_core:
  firebase_auth:
  connectivity:
  firebase_storage: ^3.0.5
  provider:
  http:
  cloud_firestore:
  font_awesome_flutter:
  intl: ^0.15.8
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/drinks/
    - lib/assets/images/menu1.png
    - lib/assets/images/menu2.png
    - lib/assets/images/menu3.png
    - lib/assets/images/menu4.png
    - lib/assets/images/menu5.png
    - lib/assets/images/menu7.png
    - lib/assets/images/menu8.png
    - lib/assets/images/menu9.png
    - lib/assets/images/menu10.png
    - lib/assets/images/menu11.png
    - lib/assets/images/menu12.png
    - lib/assets/images/menu13.png
    - lib/assets/images/menu14.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: fontello
      fonts:
        - asset: lib/assets/fonts/fontello.ttf
    - family: Dosis
      fonts:
        - asset: lib/assets/fonts/Dosis/Dosis-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Dosis/Dosis-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Dosis/Dosis-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Dosis/Dosis-Bold.ttf
          weight: 800
        - asset: lib/assets/fonts/Dosis/Dosis-ExtraBold.ttf
          weight: 900

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
